### ISSUE TITLE
Error on executing pesterchum

### ISSUE THREAD

**Issue by donutSalami** [Dpeta/pesterchum-alt-servers#84]
Computer: Windows 10
I tried opening pesterchum with both "Windows 8+" versions, but instead opens an error message:

"A profile error has occurred, trying to switch to default  pesterClient profile"

Then:

Traceback (most recent call last):
  File "profile.py", line 780, in getitem
KeyError: 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pesterchum.py", line 1207, in init
  File "profile.py", line 506, in init
  File "profile.py", line 785, in getitem
  File "profile.py", line 787, in getitem
  File "profile.py", line 780, in getitem
KeyError: 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "profile.py", line 780, in getitem
KeyError: 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pesterchum.py", line 3946, in <module>
  File "pesterchum.py", line 3636, in init
  File "pesterchum.py", line 1222, in init
  File "profile.py", line 506, in init
  File "profile.py", line 785, in getitem
  File "profile.py", line 787, in getitem
  File "profile.py", line 780, in getitem
KeyError: 'main'

**Comment by Dpeta** [comment]
The theme is missing, Pesterchum was probably not extracted correctly.
